/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.FileDialog;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.*;
/**
 *
 * @author sshj1
 */
public class ScoreMg1 extends javax.swing.JFrame {
    StudentVO clickedStudent;
    ArrayList <StudentVO> totalList = new ArrayList<>();
    ArrayList <StudentVO> searchList = new ArrayList<>();
    ArrayList <StudentVO> showList = totalList;
    int currentPageNum = 1;
    /**
     * Creates new form ScoreMg1
     */
    public ScoreMg1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInputPnl = new javax.swing.JPanel();
        jNamePnl = new javax.swing.JLabel();
        jKorPnl = new javax.swing.JLabel();
        jEngPnl = new javax.swing.JLabel();
        jMathPnl = new javax.swing.JLabel();
        jAvgPnl = new javax.swing.JLabel();
        jRankPnl = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jRankTxt = new javax.swing.JTextField();
        jMenuPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPagePnl = new javax.swing.JPanel();
        jFirstBtn = new javax.swing.JButton();
        jPrevBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPageNumBtn = new javax.swing.JButton();
        jNextBtn = new javax.swing.JButton();
        jLastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInputPnl.setBackground(new java.awt.Color(255, 102, 0));
        jInputPnl.setLayout(new java.awt.GridLayout(2, 0));

        jNamePnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamePnl.setText("이름");
        jInputPnl.add(jNamePnl);

        jKorPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKorPnl.setText("국어");
        jInputPnl.add(jKorPnl);

        jEngPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEngPnl.setText("영어");
        jInputPnl.add(jEngPnl);

        jMathPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMathPnl.setText("수학");
        jInputPnl.add(jMathPnl);

        jAvgPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAvgPnl.setText("평균");
        jInputPnl.add(jAvgPnl);

        jRankPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRankPnl.setText("석차");
        jInputPnl.add(jRankPnl);

        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jNameTxt);

        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jKorTxt);

        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jEngTxt);

        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jMathTxt);

        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jAvgTxt);

        jRankTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jRankTxt);

        jMenuPnl.setBackground(new java.awt.Color(0, 153, 204));
        jMenuPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jMenuPnl.add(jInsertBtn);

        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jMenuPnl.add(jDeleteBtn);

        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jMenuPnl.add(jDataReadBtn);

        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jMenuPnl.add(jUpdateBtn);

        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jMenuPnl.add(jSearchBtn);

        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.setToolTipText("");
        jDataWriteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDataWriteBtn.setName(""); // NOI18N
        jMenuPnl.add(jDataWriteBtn);

        jResultPnl.setBackground(new java.awt.Color(102, 0, 204));
        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        jPagePnl.setBackground(new java.awt.Color(153, 0, 153));
        jPagePnl.setLayout(new java.awt.GridLayout(1, 0));

        jFirstBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jFirstBtn.setText("<<");
        jFirstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jFirstBtn);

        jPrevBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPrevBtn.setText("<");
        jPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jPrevBtn);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPageNumBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jPageNumBtn.setText("0 / 0");
        jPageNumBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jPanel1.add(jPageNumBtn);

        jPagePnl.add(jPanel1);

        jNextBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jNextBtn.setText(">");
        jNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jNextBtn);

        jLastBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLastBtn.setText(">>");
        jLastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jLastBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInputPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMenuPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInputPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMenuPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void objectification(String data) {
        StudentVO obj = new StudentVO(data);
        totalList.add(obj);
    }
    
    private void showSearchList()   {
        currentPageNum = 1;
        showList = searchList;
        showList();
    }
    
    private void showList() {
        // jResultPnl 내용초기화    
        this.jResultPnl.removeAll();
        
        // 랭크 초기화
        for (int l = 0; l < showList.size(); l++)  {
            StudentVO rankres = showList.get(l);
            rankres.rank = 1;
        }
        
        // 랭크갱신
        for (int j = 0; j < showList.size(); j++)  {
            for (int k = 0; k < showList.size(); k++)  {
                showList.get(j).setRank(showList.get(k).getAvg());
            }
        }
        
        // 랭크 오름차순으로 sort진행(sort메서드 사용 X)
        for (int m = 0; m < showList.size(); m++)  {
            for (int n = 0; n < showList.size(); n++)   {
                StudentVO temp;
                if (showList.get(m).getRank() < showList.get(n).getRank())  {
                    temp = showList.get(m);
                    showList.set(m, showList.get(n));
                    showList.set(n, temp);
                }
            }
        }
        // jResultPnl에 JButton 생성
        for (int i = (currentPageNum-1)*5; i < (currentPageNum)*5; i++)  {
            StudentVO student = showList.get(i);
            SButton1 obj = new SButton1(student);
            this.jPageNumBtn.setText(currentPageNum +  " / " + (((showList.size()-1)/5)+1));
            this.jResultPnl.add(obj);                                   // 여기서 ResultPnl의 출력은 끝남
            // JButton이 클릭될때 발생하는 기능들 구현
            obj.addActionListener(new java.awt.event.ActionListener() { // 여기부터는 출력된 객체를 클릭했을때 j***Pnl에 값이 출력되도록 구현한 로직
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    SButton1 stu = (SButton1)e.getSource();
                    StudentVO obj2 = stu.getStudent();
                    jNameTxt.setText(obj2.getName());
                    jKorTxt.setText("" + obj2.getKor());
                    jEngTxt.setText("" + obj2.getEng());
                    jMathTxt.setText("" + obj2.getMath());
                    jAvgTxt.setText("" + obj2.getAvg());
                    jRankTxt.setText("" + obj2.getRank());
                    clickedStudent = obj2;
                }
            });
        }
        // 위에서 작업한 내용들 전부 출력 후 showList초기화 및 clickedStudent 초기화
        this.pack();
        clickedStudent = null;
    }
    // totalList에 obj넣기
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        StudentVO obj = new StudentVO(this.jNameTxt.getText() +
                " " + this.jKorTxt.getText() +
                " " + this.jEngTxt.getText() +
                " " + this.jMathTxt.getText()
                );
        totalList.add(obj);
        showList();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        if (clickedStudent == null) {
            return;
        }
        
        clickedStudent.setName(this.jNameTxt.getText());
        clickedStudent.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clickedStudent.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clickedStudent.setMath(Integer.parseInt(this.jMathTxt.getText()));
        clickedStudent.setAvg(clickedStudent.getAvg());
        clickedStudent.setRank(Integer.parseInt(this.jRankTxt.getText()));
        jAvgTxt.setText("" + clickedStudent.getAvg());
        
        showList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if (clickedStudent == null) {
            return;
        }
        
        totalList.remove(clickedStudent);
        showList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        searchList.clear();
        
        for (int i = 0; i < totalList.size(); i++)  {
            StudentVO temp = totalList.get(i);
            if (temp.getName().contains(this.jNameTxt.getText()))  {
                searchList.add(temp);
            } else if (temp.getName().equals("\\s+")) {
                showList();
            }
        }  
        
        showSearchList();
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jFirstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstBtnActionPerformed
        if (currentPageNum >= 1)    {
            currentPageNum = 1;
        }
        showList();
    }//GEN-LAST:event_jFirstBtnActionPerformed

    private void jPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevBtnActionPerformed
        if (currentPageNum > 1) {
            currentPageNum--;
        }
        showList();
    }//GEN-LAST:event_jPrevBtnActionPerformed

    private void jNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextBtnActionPerformed
        if (currentPageNum < (((showList.size()-1)/5)+1)) {
            currentPageNum++;
        }
        showList();
    }//GEN-LAST:event_jNextBtnActionPerformed

    private void jLastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastBtnActionPerformed
        if (currentPageNum <= (((showList.size()-1)/5)+1)) {
            currentPageNum = (((showList.size()-1)/5)+1);
        }
        showList();
    }//GEN-LAST:event_jLastBtnActionPerformed

    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
        FileDialog fileDialog = new FileDialog(this, "파일선택", FileDialog.LOAD); 
        fileDialog.setVisible(true);
        String filelocation = fileDialog.getDirectory() + fileDialog.getFile();
        
        try {
            Scanner scn = new Scanner(new File(filelocation));
            String data = "";
            while(true) {
                try {
                    data = scn.nextLine();
                    objectification(data);
                } catch (Exception e) {
                    break;
                }
            }
        } catch (Exception e) {
        }
        showList();
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMg1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAvgPnl;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JLabel jEngPnl;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstBtn;
    private javax.swing.JPanel jInputPnl;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JLabel jKorPnl;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastBtn;
    private javax.swing.JLabel jMathPnl;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JPanel jMenuPnl;
    private javax.swing.JLabel jNamePnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextBtn;
    private javax.swing.JButton jPageNumBtn;
    private javax.swing.JPanel jPagePnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrevBtn;
    private javax.swing.JLabel jRankPnl;
    private javax.swing.JTextField jRankTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
