
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class ScoreMg5 extends javax.swing.JFrame {
    
    StudentVO5 clickedStudent5;
    ArrayList<StudentVO5> totalList = new ArrayList<>();
    ArrayList<StudentVO5> searchList = new ArrayList<>();
    ArrayList<StudentVO5> showList = totalList;
    int currentPageNum = 1;
    
    /**
     * Creates new form ScoreMg5
     */
    public ScoreMg5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInputPnl = new javax.swing.JPanel();
        jNamePnl = new javax.swing.JLabel();
        jKorPnl = new javax.swing.JLabel();
        jEngPnl = new javax.swing.JLabel();
        jMathPnl = new javax.swing.JLabel();
        jAvgPnl = new javax.swing.JLabel();
        jRankPnl = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jRankTxt = new javax.swing.JTextField();
        jBtnPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jSerializationBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jDeserializationBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPagePnl = new javax.swing.JPanel();
        jFirstPageBtn = new javax.swing.JButton();
        jPrevPageBtn = new javax.swing.JButton();
        jWhereAmIBtn = new javax.swing.JButton();
        jNextPageBtn = new javax.swing.JButton();
        jLastPageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInputPnl.setBackground(new java.awt.Color(0, 204, 204));
        jInputPnl.setLayout(new java.awt.GridLayout(2, 0));

        jNamePnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jNamePnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamePnl.setText("이름");
        jInputPnl.add(jNamePnl);

        jKorPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jKorPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKorPnl.setText("국어");
        jInputPnl.add(jKorPnl);

        jEngPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jEngPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEngPnl.setText("영어");
        jInputPnl.add(jEngPnl);

        jMathPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMathPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMathPnl.setText("수학");
        jInputPnl.add(jMathPnl);

        jAvgPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jAvgPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAvgPnl.setText("평균");
        jInputPnl.add(jAvgPnl);

        jRankPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRankPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRankPnl.setText("석차");
        jInputPnl.add(jRankPnl);

        jNameTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jNameTxt);

        jKorTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jKorTxt);

        jEngTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jEngTxt);

        jMathTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jMathTxt);

        jAvgTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jAvgTxt);

        jRankTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRankTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputPnl.add(jRankTxt);

        jBtnPnl.setBackground(new java.awt.Color(153, 51, 0));
        jBtnPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jInsertBtn);

        jDeleteBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jDeleteBtn);

        jDataReadBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jDataReadBtn);

        jSerializationBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jSerializationBtn.setText("직렬화");
        jSerializationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerializationBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jSerializationBtn);

        jUpdateBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jUpdateBtn);

        jSearchBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jSearchBtn);

        jDataWriteBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jDataWriteBtn);

        jDeserializationBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDeserializationBtn.setText("역직렬화");
        jDeserializationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeserializationBtnActionPerformed(evt);
            }
        });
        jBtnPnl.add(jDeserializationBtn);

        jResultPnl.setBackground(new java.awt.Color(0, 102, 153));
        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        jPagePnl.setBackground(new java.awt.Color(0, 153, 153));
        jPagePnl.setLayout(new java.awt.GridLayout(1, 0));

        jFirstPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jFirstPageBtn.setText("<<");
        jFirstPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jFirstPageBtn);

        jPrevPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPrevPageBtn.setText("<");
        jPrevPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jPrevPageBtn);

        jWhereAmIBtn.setBackground(new java.awt.Color(204, 0, 255));
        jWhereAmIBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPagePnl.add(jWhereAmIBtn);

        jNextPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jNextPageBtn.setText(">");
        jNextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jNextPageBtn);

        jLastPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLastPageBtn.setText(">>");
        jLastPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jLastPageBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInputPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInputPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void showTotalList()    {
        showList = totalList;
        showList();
    }
    
    private void showSearchList()    {
        showList = searchList;
        showList();
    }
    
    private void showList() {
        this.jResultPnl.removeAll();
        
        for (int j = 0; j < showList.size(); j++)   {
            showList.get(j).rank = 1;
        }
        
        for (int k = 0; k < showList.size(); k++)   {
            for (int l = 0; l < showList.size(); l++)   {
                showList.get(k).setRank(showList.get(l).getAvg());
            }
        }
        
        for (int m = 0; m < showList.size(); m++)   {
            for (int n = 0; n < showList.size(); n++)   {
                StudentVO5 tmp;
                if (showList.get(m).rank < showList.get(n).rank)    {
                    tmp = showList.get(m);
                    showList.set(m, showList.get(n));
                    showList.set(n, tmp);
                }
            }
        }
        
        try {
            for (int i = (currentPageNum-1)*5; i < currentPageNum*5; i++)   {
            SButton5 obj = new SButton5(showList.get(i));
            this.jResultPnl.add(obj);
            obj.setBackground(new java.awt.Color(204, 0, 255));
            this.jWhereAmIBtn.setText(currentPageNum + " / " + (((showList.size()-1)/5)+1));
            
            obj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButton5 click = (SButton5)evt.getSource();
                StudentVO5 stu = click.getStudent();
                
                jNameTxt.setText(stu.getName());
                jKorTxt.setText("" + stu.getKor());
                jEngTxt.setText("" + stu.getEng());
                jMathTxt.setText("" + stu.getMath());
                jAvgTxt.setText("" + stu.getAvg());
                jRankTxt.setText("" + stu.getRank());
                clickedStudent5 = stu;
            }
        });
        }
        } catch (Exception e) {
        }
        
        this.pack();
        clickedStudent5 = null;
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        StudentVO5 student5 = new StudentVO5(this.jNameTxt.getText(),
                                             Integer.parseInt(this.jKorTxt.getText()),
                                             Integer.parseInt(this.jEngTxt.getText()),
                                             Integer.parseInt(this.jMathTxt.getText()));
        totalList.add(student5);
        showTotalList();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        clickedStudent5.setName(this.jNameTxt.getText());
        clickedStudent5.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clickedStudent5.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clickedStudent5.setMath(Integer.parseInt(this.jMathTxt.getText()));
        clickedStudent5.setRank(Integer.parseInt(this.jRankTxt.getText()));
        clickedStudent5.setAvg();
        
        showTotalList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if(clickedStudent5 == null) {
            return;
        }
        
        totalList.remove(clickedStudent5);
        showTotalList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        if (clickedStudent5 == null) {
            return;
        }
        
        for (int i = 0; i < totalList.size(); i++)  {
            if(totalList.get(i).getName().contains(this.jNameTxt.getText()))    {
                searchList.add(totalList.get(i));
            }
        }
        
        showSearchList();
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jFirstPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstPageBtnActionPerformed
        if(currentPageNum >= 1) {
            currentPageNum = 1;
        }
        
        showList();
    }//GEN-LAST:event_jFirstPageBtnActionPerformed

    private void jPrevPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevPageBtnActionPerformed
        if(currentPageNum > 1)  {
            currentPageNum--;
        }
        
        showList();
    }//GEN-LAST:event_jPrevPageBtnActionPerformed

    private void jNextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPageBtnActionPerformed
        if (currentPageNum*5 < showList.size()) {
            currentPageNum++;
        }
        
        showList();
    }//GEN-LAST:event_jNextPageBtnActionPerformed

    private void jLastPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastPageBtnActionPerformed
        if (currentPageNum < ((showList.size()-1)/5)+1) {
            currentPageNum = ((showList.size()-1)/5)+1;
        }
        
        showList();
    }//GEN-LAST:event_jLastPageBtnActionPerformed
    
    private void objectification(String info)   {
        StudentVO5 obj = new StudentVO5(info);
        totalList.add(obj);
    }
    
    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
          FileDialog find = new FileDialog(this, "파일읽기", FileDialog.LOAD);
          find.setVisible(true);
          String fileinfo = find.getDirectory() + find.getFile();
          
          try {
              Scanner scn = new Scanner(new File(fileinfo));
              String info = "";
              while(true)   {
                try {
                    info = scn.nextLine();
                    objectification(info);
                } catch (Exception e) {
                    break;
                }
              }
        } catch (Exception e) {
        }

//        String filename = "Scores5.dat";
//        
//        try {
//            BufferedReader br = new BufferedReader(new FileReader(filename));
//            String data = "";
//            while(true) {
//                data = br.readLine();
//                objectification(data);
//            }
//        } catch (Exception e) {
//        }
//        
        showTotalList();
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jDataWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteBtnActionPerformed
        FileDialog find = new FileDialog(this, "파일쓰기", FileDialog.SAVE);
        find.setVisible(true);
        String filename = find.getDirectory() + find.getFile() + ".txt";

//        String filename = "Scores5.dat";
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(filename, false));
            for (int i = 0; i < totalList.size(); i++)  {
                StudentVO5 info = totalList.get(i);
                bw.write(info.getName() + " ");
                bw.write(info.getKor() + " ");
                bw.write(info.getEng() + " ");
                bw.write(info.getMath() + "");
                bw.newLine();
            }
            
            bw.flush();
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jDataWriteBtnActionPerformed

    private void jSerializationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerializationBtnActionPerformed
        FileDialog find = new FileDialog(this, "직렬화", FileDialog.SAVE);
        find.setVisible(true);
        String sfilename = find.getDirectory() + find.getFile() + ".ser";
        
//        String sfilename = "Scores5.ser";
        try {
            FileOutputStream fos = new FileOutputStream(sfilename, false);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            
            for (int i = 0; i < totalList.size(); i++)  {
                oos.writeObject(totalList.get(i));
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSerializationBtnActionPerformed

    private void jDeserializationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeserializationBtnActionPerformed
        FileDialog find = new FileDialog(this, "역직렬화", FileDialog.LOAD);
        find.setVisible(true);
        String dfilename = find.getDirectory() + find.getFile();

//        String dfilename = "Scores5.ser";
        try {
            FileInputStream fis = new FileInputStream(dfilename);
            ObjectInputStream ois = new ObjectInputStream(fis);
            
            while(true) {
                try {
                    StudentVO5 readed = (StudentVO5)ois.readObject();
                    totalList.add(readed);
                } catch (Exception e) {
                    break;
                }
            }
        } catch (Exception e) {
        }
        
        showTotalList();
    }//GEN-LAST:event_jDeserializationBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMg5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAvgPnl;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JPanel jBtnPnl;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JButton jDeserializationBtn;
    private javax.swing.JLabel jEngPnl;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstPageBtn;
    private javax.swing.JPanel jInputPnl;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JLabel jKorPnl;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastPageBtn;
    private javax.swing.JLabel jMathPnl;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JLabel jNamePnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextPageBtn;
    private javax.swing.JPanel jPagePnl;
    private javax.swing.JButton jPrevPageBtn;
    private javax.swing.JLabel jRankPnl;
    private javax.swing.JTextField jRankTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jSerializationBtn;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JButton jWhereAmIBtn;
    // End of variables declaration//GEN-END:variables
}
