
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class ScoreMg3 extends javax.swing.JFrame {
    StudentVO3 clickedStudent;
    ArrayList <StudentVO3> totalList = new ArrayList<>();
    ArrayList <StudentVO3> searchList = new ArrayList<>();
    ArrayList <StudentVO3> showList = totalList;
    int currentPageNum3 = 1;
    /**
     * Creates new form ScoreMg3
     */
    public ScoreMg3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInfoPnl = new javax.swing.JPanel();
        jNamePnl = new javax.swing.JLabel();
        jKorPnl = new javax.swing.JLabel();
        jEngPnl = new javax.swing.JLabel();
        jMathPnl = new javax.swing.JLabel();
        jAvgPnl = new javax.swing.JLabel();
        jRankPnl = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jRankTxt = new javax.swing.JTextField();
        jActionPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jSerializeBtn = new javax.swing.JButton();
        jDeleteAllBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jDeserializeBtn = new javax.swing.JButton();
        jSeeAllDataBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPageNumPnl = new javax.swing.JPanel();
        jFirstPageBtn = new javax.swing.JButton();
        jPrevPageBtn = new javax.swing.JButton();
        jWhereAmI = new javax.swing.JButton();
        jNextPageBtn = new javax.swing.JButton();
        jLastPageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInfoPnl.setBackground(new java.awt.Color(102, 102, 102));
        jInfoPnl.setLayout(new java.awt.GridLayout(2, 0));

        jNamePnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jNamePnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamePnl.setText("이름");
        jInfoPnl.add(jNamePnl);

        jKorPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jKorPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKorPnl.setText("국어");
        jInfoPnl.add(jKorPnl);

        jEngPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jEngPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEngPnl.setText("영어");
        jInfoPnl.add(jEngPnl);

        jMathPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMathPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMathPnl.setText("수학");
        jInfoPnl.add(jMathPnl);

        jAvgPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jAvgPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAvgPnl.setText("평균");
        jInfoPnl.add(jAvgPnl);

        jRankPnl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRankPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRankPnl.setText("석차");
        jInfoPnl.add(jRankPnl);

        jNameTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jNameTxt);

        jKorTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jKorTxt);

        jEngTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jEngTxt);

        jMathTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jMathTxt);

        jAvgTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jAvgTxt);

        jRankTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jRankTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jRankTxt);

        jActionPnl.setBackground(new java.awt.Color(0, 153, 153));
        jActionPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jInsertBtn);

        jDeleteBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDeleteBtn);

        jDataReadBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDataReadBtn);

        jSerializeBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jSerializeBtn.setText("직렬화");
        jSerializeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerializeBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jSerializeBtn);

        jDeleteAllBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jDeleteAllBtn.setText("전체삭제");
        jDeleteAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteAllBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDeleteAllBtn);

        jUpdateBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jUpdateBtn);

        jSearchBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jSearchBtn);

        jDataWriteBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDataWriteBtn);

        jDeserializeBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jDeserializeBtn.setText("역직렬화");
        jDeserializeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeserializeBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDeserializeBtn);

        jSeeAllDataBtn.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jSeeAllDataBtn.setText("전체보기");
        jSeeAllDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeeAllDataBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jSeeAllDataBtn);

        jResultPnl.setBackground(new java.awt.Color(153, 0, 102));
        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        jPageNumPnl.setBackground(new java.awt.Color(0, 102, 0));
        jPageNumPnl.setLayout(new java.awt.GridLayout(0, 5));

        jFirstPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jFirstPageBtn.setText("<<");
        jFirstPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstPageBtnActionPerformed(evt);
            }
        });
        jPageNumPnl.add(jFirstPageBtn);

        jPrevPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPrevPageBtn.setText("<");
        jPrevPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevPageBtnActionPerformed(evt);
            }
        });
        jPageNumPnl.add(jPrevPageBtn);

        jWhereAmI.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jWhereAmI.setText("데이터 X");
        jPageNumPnl.add(jWhereAmI);

        jNextPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jNextPageBtn.setText(">");
        jNextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPageBtnActionPerformed(evt);
            }
        });
        jPageNumPnl.add(jNextPageBtn);

        jLastPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLastPageBtn.setText(">>");
        jLastPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastPageBtnActionPerformed(evt);
            }
        });
        jPageNumPnl.add(jLastPageBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jActionPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPageNumPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jActionPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPageNumPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showList() {
        this.jResultPnl.removeAll();
        
        for (int j = 0; j < showList.size(); j++)   {
            showList.get(j).rank = 1;
        }
        
        for (int k = 0; k < showList.size(); k++)   {
            for (int l = 0; l < showList.size(); l++)   {
                showList.get(k).setRank(showList.get(l).getAvg());   
            }
        }
        
        for (int m = 0; m < showList.size(); m++)   {
            for (int n = 0; n < showList.size(); n++)   {
                StudentVO3 tmp;
                StudentVO3 a = showList.get(m);
                StudentVO3 b = showList.get(n);
                if (a.rank < b.rank)    {
                    tmp = a;
                    showList.set(m, b);
                    showList.set(n, tmp);
                }
            }
        }
        
        for (int i = (currentPageNum3-1)*5; i < currentPageNum3*5; i++)   {
            try {
                StudentVO3 students = showList.get(i);
                SButton3 obj2 = new SButton3(students);
                this.jResultPnl.add(obj2);
                this.jWhereAmI.setText(currentPageNum3 + " / " + (((showList.size()-1)/5)+1));
                
                obj2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SButton3 click = (SButton3)evt.getSource();
                    StudentVO3 obj3 = click.getStudent();
                    jNameTxt.setText(obj3.getName());
                    jKorTxt.setText("" + obj3.getKor());
                    jEngTxt.setText("" + obj3.getEng());
                    jMathTxt.setText("" + obj3.getMath());
                    jAvgTxt.setText("" + obj3.getAvg());
                    jRankTxt.setText("" + obj3.getRank());
                    clickedStudent = obj3;
                    }
                });       
            } catch (Exception e) {
                break;
            }
        }
        this.pack();
        clickedStudent = null;
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        StudentVO3 student = new StudentVO3(this.jNameTxt.getText(),
                                            Integer.parseInt(this.jKorTxt.getText()),
                                            Integer.parseInt(this.jEngTxt.getText()), 
                                            Integer.parseInt(this.jMathTxt.getText()));
        
        totalList.add(student);
        if (totalList.size() % 5 != 0)  {
            currentPageNum3 = ((showList.size()-1)/5)+1;
        }
        showList();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        if(clickedStudent == null)  {
            return;
        }
        
        clickedStudent.setName(this.jNameTxt.getText());
        clickedStudent.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clickedStudent.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clickedStudent.setMath(Integer.parseInt(this.jMathTxt.getText()));
        clickedStudent.getAvg();
        
        showList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if(clickedStudent == null)  {
            return;
        }
        
        totalList.remove(clickedStudent);
        if (totalList.size() % 5 == 0)  {
            currentPageNum3--;
        }
        showList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        searchList.clear();
        
        for (int i = 0; i < totalList.size(); i++)  {
            if (this.jNameTxt.getText().contains(totalList.get(i).getName()))   {
                searchList.add(totalList.get(i));
            }
        }
        
        showSearchList();
    }//GEN-LAST:event_jSearchBtnActionPerformed
    
    private void showSearchList()   {
        showList = searchList;
        showList();
    }
    
    private void showTotalList()    {
        showList = totalList;
        showList();
    }
    
    private void objectification(String file)   {
        StudentVO3 read = new StudentVO3(file);
        totalList.add(read);
    }
    
    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
        totalList.clear();
        try {
            BufferedReader br;
            br = new BufferedReader(new FileReader("Scores.dat"));
            String read = "";
            
            while(true) {
                try {
                    read = br.readLine();
                    objectification(read);
                } catch (Exception e) {
                    break;
                }
            }
        } catch (Exception e) {         
        }
        
        showList();
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jFirstPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstPageBtnActionPerformed
        if(currentPageNum3 >= 1) {
            currentPageNum3 = 1;
        }
        
        showList();
    }//GEN-LAST:event_jFirstPageBtnActionPerformed

    private void jPrevPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevPageBtnActionPerformed
        if (currentPageNum3 > 1)   {
            currentPageNum3--;
        }
        
        showList();
    }//GEN-LAST:event_jPrevPageBtnActionPerformed

    private void jNextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPageBtnActionPerformed
        if (currentPageNum3 * 5 < showList.size())  {
            currentPageNum3++;
        }
        
        showList();
    }//GEN-LAST:event_jNextPageBtnActionPerformed

    private void jLastPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastPageBtnActionPerformed
        if (currentPageNum3 < ((showList.size()-1)/5)+1)    {
            currentPageNum3 =  ((showList.size()-1)/5)+1;
        }
        
        showList();
    }//GEN-LAST:event_jLastPageBtnActionPerformed
    // 직렬화
    private void jSerializeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerializeBtnActionPerformed
        String filename = "Scores.ser";
        
        try
        {
            FileOutputStream fos = new FileOutputStream(filename);
            ObjectOutputStream out = new ObjectOutputStream(fos);
            for (int i = 0; i < totalList.size(); i++)  {
                out.writeObject(totalList.get(i));
            }
        } catch (Exception e) {
            System.out.println("직렬화 실패");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jSerializeBtnActionPerformed
    // 역직렬화
    private void jDeserializeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeserializeBtnActionPerformed
        totalList.clear();
        
        String filename = "Scores.ser";
        
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream in = new ObjectInputStream(fis);
            
            while(true) {
                try {
                    StudentVO3 deSerializedstu = (StudentVO3)in.readObject();
                    totalList.add(deSerializedstu);
                } catch (Exception e) {
                    break;
                }
            }
            System.out.println("역직렬화 완료");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("역직렬화 실패");
        }
        
        showList();
    }//GEN-LAST:event_jDeserializeBtnActionPerformed

    private void jDataWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteBtnActionPerformed
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("Scores.dat", false));
            for (int i = 0; i < totalList.size(); i++)  {
                bw.write(totalList.get(i).getName() + " ");
                bw.write(totalList.get(i).getKor() + " ");
                bw.write(totalList.get(i).getEng() + " ");
                bw.write(totalList.get(i).getMath() + "");
                bw.newLine();
            }
            bw.flush();
            bw.close();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jDataWriteBtnActionPerformed

    private void jDeleteAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteAllBtnActionPerformed
        totalList.clear();
        searchList.clear();
        showList();
    }//GEN-LAST:event_jDeleteAllBtnActionPerformed

    private void jSeeAllDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeeAllDataBtnActionPerformed
        showList();
    }//GEN-LAST:event_jSeeAllDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMg3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jActionPnl;
    private javax.swing.JLabel jAvgPnl;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteAllBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JButton jDeserializeBtn;
    private javax.swing.JLabel jEngPnl;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstPageBtn;
    private javax.swing.JPanel jInfoPnl;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JLabel jKorPnl;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastPageBtn;
    private javax.swing.JLabel jMathPnl;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JLabel jNamePnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextPageBtn;
    private javax.swing.JPanel jPageNumPnl;
    private javax.swing.JButton jPrevPageBtn;
    private javax.swing.JLabel jRankPnl;
    private javax.swing.JTextField jRankTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jSeeAllDataBtn;
    private javax.swing.JButton jSerializeBtn;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JButton jWhereAmI;
    // End of variables declaration//GEN-END:variables
}
