
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class ScoreMg4 extends javax.swing.JFrame {
    StudentVO4 clickedStudent;
    ArrayList<StudentVO4> totalList = new ArrayList<>();
    ArrayList<StudentVO4> searchList = new ArrayList<>();
    ArrayList<StudentVO4> showList = totalList;
    int currentPageNum = 1;
    
    /**
     * Creates new form ScoreMg4
     */
    public ScoreMg4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jNamePnl = new javax.swing.JLabel();
        jKorPnl = new javax.swing.JLabel();
        jEngPnl = new javax.swing.JLabel();
        jMathPnl = new javax.swing.JLabel();
        jAvgPnl = new javax.swing.JLabel();
        jRankPnl = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jRankTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jInsetBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jSerializeBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jDeserializeBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jFirstPageBtn = new javax.swing.JButton();
        jPrevPageBtn = new javax.swing.JButton();
        jWhereAmIBtn = new javax.swing.JButton();
        jNextPageBtn = new javax.swing.JButton();
        jLastPageBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jNamePnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jNamePnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamePnl.setText("이름");
        jPanel1.add(jNamePnl);

        jKorPnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jKorPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKorPnl.setText("국어");
        jPanel1.add(jKorPnl);

        jEngPnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jEngPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEngPnl.setText("영어");
        jPanel1.add(jEngPnl);

        jMathPnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jMathPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMathPnl.setText("수학");
        jPanel1.add(jMathPnl);

        jAvgPnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jAvgPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAvgPnl.setText("평균");
        jPanel1.add(jAvgPnl);

        jRankPnl.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jRankPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRankPnl.setText("석차");
        jPanel1.add(jRankPnl);

        jNameTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jNameTxt);

        jKorTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jKorTxt);

        jEngTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jEngTxt);

        jMathTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jMathTxt);

        jAvgTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jAvgTxt);

        jRankTxt.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jRankTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jRankTxt);

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jInsetBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jInsetBtn.setText("추가하기");
        jInsetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jInsetBtn);

        jDeleteBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteBtn);

        jDataReadBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDataReadBtn);

        jSerializeBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jSerializeBtn.setText("직렬화");
        jSerializeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerializeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jSerializeBtn);

        jUpdateBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateBtn);

        jSearchBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jSearchBtn);

        jDataWriteBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDataWriteBtn);

        jDeserializeBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDeserializeBtn.setText("역직렬화");
        jDeserializeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeserializeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDeserializeBtn);

        jResultPnl.setBackground(new java.awt.Color(0, 0, 0));
        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jFirstPageBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jFirstPageBtn.setText("<<");
        jFirstPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstPageBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jFirstPageBtn);

        jPrevPageBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jPrevPageBtn.setText("<");
        jPrevPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevPageBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jPrevPageBtn);

        jWhereAmIBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jPanel4.add(jWhereAmIBtn);

        jNextPageBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jNextPageBtn.setText(">");
        jNextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPageBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jNextPageBtn);

        jLastPageBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLastPageBtn.setText(">>");
        jLastPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastPageBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jLastPageBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showTotalList()    {
        showList = totalList;
        showList();
    }
    
    private void showSearchList()    {
        showList = searchList;
        showList();
    }
    
    private void showList()    {
        this.jResultPnl.removeAll();
        
        for (int i = 0; i < showList.size(); i++)   {
            showList.get(i).rank = 1;
        }
        
        for (int j = 0; j < showList.size(); j++)   {
            for (int k = 0; k < showList.size(); k++)   {
                showList.get(j).setRank(showList.get(k).getAvg());
            }
        }
        
        for (int l = 0; l < showList.size(); l++)   {
            for (int m = 0; m < showList.size(); m++)   {
                if (showList.get(l).getRank() < showList.get(m).getRank())  {
                    StudentVO4 tmp = showList.get(l);
                    showList.set(l, showList.get(m));
                    showList.set(m, tmp);
                }
            }
        }
        try {
            for (int n = (currentPageNum-1)*5; n < currentPageNum*5; n++)   {
                SButton4 obj = new SButton4(showList.get(n));
                this.jResultPnl.add(obj);
                jWhereAmIBtn.setText(currentPageNum + " / " + (((showList.size()-1)/5)+1));
                obj.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SButton4 click = (SButton4)evt.getSource();
                    StudentVO4 stu = click.getStudent();
                    jNameTxt.setText(stu.getName());
                    jKorTxt.setText("" + stu.getKor());
                    jEngTxt.setText("" + stu.getEng());
                    jMathTxt.setText("" + stu.getMath());
                    jAvgTxt.setText("" + stu.getAvg());
                    jRankTxt.setText("" + stu.getRank());
                    clickedStudent = stu;
                }
            });
            }
        }
        catch (Exception e) {
        }
        this.pack();
        clickedStudent = null;
    }
    
    private void jInsetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsetBtnActionPerformed
        StudentVO4 obj = new StudentVO4(this.jNameTxt.getText(),
                        Integer.parseInt(this.jKorTxt.getText()),
                        Integer.parseInt(this.jEngTxt.getText()),
                        Integer.parseInt(this.jMathTxt.getText()));
        totalList.add(obj);
        showTotalList();
    }//GEN-LAST:event_jInsetBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        clickedStudent.setName(this.jNameTxt.getText());
        clickedStudent.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clickedStudent.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clickedStudent.setMath(Integer.parseInt(this.jMathTxt.getText()));
        clickedStudent.getAvg();
        
        showTotalList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if(clickedStudent == null)  {
            return;
        }
        
        totalList.remove(clickedStudent);
        if(showList.size() % 5 == 0)    {
            currentPageNum--;
        }
        showTotalList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        searchList.clear();
        
        for (int i = 0; i < totalList.size(); i++)  {
            if (totalList.get(i).getName().contains(this.jNameTxt.getText())) {
                searchList.add(totalList.get(i));
            }
        }
        
        showSearchList();
        showList = totalList;
    }//GEN-LAST:event_jSearchBtnActionPerformed
        
    private void objectification(String value)  {
        StudentVO4 obj = new StudentVO4(value);
        totalList.add(obj);
    }
    
    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
          FileDialog search = new FileDialog(this, "파일 읽어오기", FileDialog.LOAD);
          search.setVisible(true);
          String fileinfo = search.getDirectory() + search.getFile();
          
          try {
              Scanner scn = new Scanner(new File(fileinfo));
              String info = "";
              while(true)   {
                try {
                    info = scn.nextLine();
                    objectification(info);
                } catch (Exception e) {
                    break;
                }  
              }
            } catch (Exception e) {
            }
          showList();

//        String fileinfo = "Scores4.dat";
//        
//        try {
//            BufferedReader br = new BufferedReader(new FileReader(fileinfo));
//            String info = "";
//            while(true) {
//                try {
//                    info = br.readLine();
//                    objectification(info);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                    break;
//                }
//            }
//        } catch (FileNotFoundException ex) {
//            ex.printStackTrace();
//        }
//        
//        showList();
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jDataWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteBtnActionPerformed
        FileDialog search = new FileDialog(this, "파일쓰기", FileDialog.SAVE);
        search.setVisible(true);
        String loc = search.getDirectory();
        String fname = search.getFile();
        String finstr = loc + fname + "." + "dat";
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(finstr));
                    for (int i = 0; i < totalList.size(); i++)  {
                        bw.write(totalList.get(i).getName() + " ");
                        bw.write(totalList.get(i).getKor() + " ");
                        bw.write(totalList.get(i).getEng() + " ");
                        bw.write(totalList.get(i).getMath() + "");
                        bw.newLine();
                    }
                bw.flush();
                bw.close();
            } catch (Exception e)   {
                e.printStackTrace();
            }
//            
//            
//            
//       String fileinfo = "Scores4.dat";
//        
//       try {
//           BufferedWriter bw = new BufferedWriter(new FileWriter(fileinfo, false));
//           for (int i = 0; i < totalList.size(); i++)  {
//                bw.write(totalList.get(i).getName() + " ");
//                bw.write(totalList.get(i).getKor() + " ");
//                bw.write(totalList.get(i).getEng() + " ");
//                bw.write(totalList.get(i).getMath()+ "");
//                bw.newLine();
//            }
//            bw.flush();
//            bw.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jDataWriteBtnActionPerformed

    private void jSerializeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerializeBtnActionPerformed
        String filename = "Scores4.ser";
        
        try 
        {
            FileOutputStream fos = new FileOutputStream(filename);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            
            for (int i = 0; i < totalList.size(); i++)  {
                oos.writeObject(totalList.get(i));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jSerializeBtnActionPerformed

    private void jDeserializeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeserializeBtnActionPerformed
        String filename = "Scores4.ser";
        
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream ois = new ObjectInputStream(fis);
            while(true) {
                try {
                    StudentVO4 obj = (StudentVO4)ois.readObject();
                    totalList.add(obj);
                } catch (Exception e) {
                    break;
                }
            }
        } catch (Exception e) {
        }
        showList();
    }//GEN-LAST:event_jDeserializeBtnActionPerformed

    private void jFirstPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstPageBtnActionPerformed
        if (currentPageNum >= 1)    {
            currentPageNum = 1;
        }
        
        showList();
    }//GEN-LAST:event_jFirstPageBtnActionPerformed

    private void jPrevPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevPageBtnActionPerformed
        if (currentPageNum > 1) {
            currentPageNum--;
        }
        
        showList();
    }//GEN-LAST:event_jPrevPageBtnActionPerformed

    private void jNextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPageBtnActionPerformed
        if (currentPageNum*5 < showList.size()) {
            currentPageNum++;
        }
        
        showList();
    }//GEN-LAST:event_jNextPageBtnActionPerformed

    private void jLastPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastPageBtnActionPerformed
        if (currentPageNum < ((showList.size()-1)/5)+1) {
            currentPageNum = (((showList.size()-1)/5)+1);
        }
        
        showList();
    }//GEN-LAST:event_jLastPageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMg4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAvgPnl;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JButton jDeserializeBtn;
    private javax.swing.JLabel jEngPnl;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstPageBtn;
    private javax.swing.JButton jInsetBtn;
    private javax.swing.JLabel jKorPnl;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastPageBtn;
    private javax.swing.JLabel jMathPnl;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JLabel jNamePnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextPageBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jPrevPageBtn;
    private javax.swing.JLabel jRankPnl;
    private javax.swing.JTextField jRankTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jSerializeBtn;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JButton jWhereAmIBtn;
    // End of variables declaration//GEN-END:variables
}
