
import java.awt.FileDialog;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class ScoreMg2 extends javax.swing.JFrame {
    StudentVO2 clickedStudent2;
    ArrayList <StudentVO2> totalList = new ArrayList<>();
    ArrayList <StudentVO2> searchList = new ArrayList<>();
    ArrayList <StudentVO2> showList = totalList;
    int currentPageNum = 1;
    
    /**
     * Creates new form ScoreMg2
     */
    public ScoreMg2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInfoPnl = new javax.swing.JPanel();
        jNamePnl = new javax.swing.JLabel();
        jKorPnl = new javax.swing.JLabel();
        jEngPnl = new javax.swing.JLabel();
        jMathPnl = new javax.swing.JLabel();
        jAvgPnl = new javax.swing.JLabel();
        jRankPnl = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jRankTxt = new javax.swing.JTextField();
        jActionPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jWriteBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPagePnl = new javax.swing.JPanel();
        jFirstPageBtn = new javax.swing.JButton();
        jPrevPageBtn = new javax.swing.JButton();
        jWherePageBtn = new javax.swing.JButton();
        jNextPageBtn = new javax.swing.JButton();
        jLastPageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInfoPnl.setBackground(new java.awt.Color(0, 153, 204));
        jInfoPnl.setLayout(new java.awt.GridLayout(2, 0));

        jNamePnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jNamePnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNamePnl.setText("이름");
        jInfoPnl.add(jNamePnl);

        jKorPnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jKorPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKorPnl.setText("국어성적");
        jInfoPnl.add(jKorPnl);

        jEngPnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jEngPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEngPnl.setText("영어성적");
        jInfoPnl.add(jEngPnl);

        jMathPnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jMathPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMathPnl.setText("수학성적");
        jInfoPnl.add(jMathPnl);

        jAvgPnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jAvgPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAvgPnl.setText("평균");
        jInfoPnl.add(jAvgPnl);

        jRankPnl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jRankPnl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRankPnl.setText("석차");
        jInfoPnl.add(jRankPnl);

        jNameTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jNameTxt);

        jKorTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jKorTxt);

        jEngTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jEngTxt);

        jMathTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jMathTxt);

        jAvgTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jAvgTxt);

        jRankTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRankTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInfoPnl.add(jRankTxt);

        jActionPnl.setBackground(new java.awt.Color(204, 204, 0));
        jActionPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jInsertBtn);

        jDeleteBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDeleteBtn);

        jDataReadBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jDataReadBtn);

        jUpdateBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jUpdateBtn);

        jSearchBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jSearchBtn);

        jWriteBtn.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jWriteBtn.setText("파일쓰기");
        jWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWriteBtnActionPerformed(evt);
            }
        });
        jActionPnl.add(jWriteBtn);

        jResultPnl.setBackground(new java.awt.Color(0, 102, 204));
        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        jPagePnl.setBackground(new java.awt.Color(0, 0, 0));
        jPagePnl.setLayout(new java.awt.GridLayout(1, 0));

        jFirstPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jFirstPageBtn.setText("<<");
        jFirstPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jFirstPageBtn);

        jPrevPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPrevPageBtn.setText("<");
        jPrevPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jPrevPageBtn);

        jWherePageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jPagePnl.add(jWherePageBtn);

        jNextPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jNextPageBtn.setText(">");
        jNextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jNextPageBtn);

        jLastPageBtn.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLastPageBtn.setText(">>");
        jLastPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastPageBtnActionPerformed(evt);
            }
        });
        jPagePnl.add(jLastPageBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
            .addComponent(jActionPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jActionPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showSearchList()   {
        currentPageNum = 1;
        showList = searchList;
        showList();
    }
    
    private void showTotalList()    {
        currentPageNum = 1;
        showList = totalList;
        showList();
    }
    
    private void showList() {
        this.jResultPnl.removeAll();
        for (int n = 0; n < showList.size(); n++)   {
            showList.get(n).rank = 1;
        }
        
        for (int j = 0; j < showList.size(); j++)   {
            for (int k = 0; k < showList.size(); k++)   {
                showList.get(j).setRank(showList.get(k).getAvg());
            }
        }
        
        for (int l = 0; l < showList.size(); l++)   {
            for (int m = 0; m < showList.size(); m++)   {
                StudentVO2 tmp = showList.get(l);
                StudentVO2 tmp2 = showList.get(m);
                if (tmp.rank < tmp2.rank)   {
                    StudentVO2 tmp3;
                    tmp3 = tmp;
                    showList.set(l, tmp2);
                    showList.set(m, tmp3);
                }    
            }
        }
        
        for (int i = (currentPageNum-1)*5; i < currentPageNum*5; i++)   {
            try {
                StudentVO2 student = showList.get(i);
                SButton2 btn = new SButton2(student);
                this.jResultPnl.add(btn);
                this.jWherePageBtn.setText(currentPageNum + " / " + (((showList.size()-1)/5)+1));
                
                btn.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SButton2 stu = (SButton2)evt.getSource();
                    StudentVO2 inf = stu.getStudent();
                    jNameTxt.setText(inf.getName());
                    jKorTxt.setText("" + inf.getKor());
                    jEngTxt.setText("" + inf.getEng());
                    jMathTxt.setText("" + inf.getMath());
                    jRankTxt.setText("" + inf.getRank());
                    jAvgTxt.setText("" + inf.getAvg());
                    clickedStudent2 = inf;
            }
        });
            } catch (Exception e) {
                break;
            }
            
        }
        this.pack();
        clickedStudent2 = null;
    }
    
    private void objectification(String value)  {
        StudentVO2 data = new StudentVO2(value);
        totalList.add(data);
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        StudentVO2 student2 = new StudentVO2(this.jNameTxt.getText() 
                        , Integer.parseInt(this.jKorTxt.getText()) 
                        , Integer.parseInt(this.jEngTxt.getText()) 
                        , Integer.parseInt(this.jMathTxt.getText()));
        
        totalList.add(student2);
        showTotalList();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        if (clickedStudent2 == null)    {
            return;
        }
        
        clickedStudent2.setName(this.jNameTxt.getText());
        clickedStudent2.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clickedStudent2.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clickedStudent2.setMath(Integer.parseInt(this.jMathTxt.getText()));
        clickedStudent2.setRank(Integer.parseInt(this.jRankTxt.getText()));
        clickedStudent2.setAvg(Double.parseDouble(this.jAvgTxt.getText()));
        
        showTotalList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if(clickedStudent2 == null) {
            return;
        }
        totalList.remove(clickedStudent2);
        showTotalList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        searchList.clear();
        
        for (int i = 0; i < totalList.size(); i++)  {
            if (this.jNameTxt.getText().contains(totalList.get(i).getName()))   {
                searchList.add(totalList.get(i));
            }
        }
        
        showSearchList();
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
        FileDialog find = new FileDialog(this, "파일로드", FileDialog.LOAD);
        find.setVisible(true);
        String location = find.getDirectory() + find.getFile();
        
        try {
            Scanner scn = new Scanner(new File(location));
            String info = "";
            while(true) {
                try {
                    info = scn.nextLine();
                    objectification(info);
                } catch (Exception e) {
                    break;
                }
            }
        } catch (Exception e) {
        }
        
        showTotalList();
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jFirstPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstPageBtnActionPerformed
       if (currentPageNum >= 1) {
           currentPageNum = 1;
       }
       showList();
    }//GEN-LAST:event_jFirstPageBtnActionPerformed

    private void jPrevPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevPageBtnActionPerformed
        if (currentPageNum > 1)    {
            currentPageNum--;
        }
        showList();
    }//GEN-LAST:event_jPrevPageBtnActionPerformed

    private void jNextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPageBtnActionPerformed
        if (currentPageNum*5 < showList.size()) {
            currentPageNum++;
        }
        showList();
    }//GEN-LAST:event_jNextPageBtnActionPerformed

    private void jLastPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastPageBtnActionPerformed
        if (currentPageNum <= showList.size()/5) {
            currentPageNum = (((showList.size()-1)/5)+1);
        }
        showList();
    }//GEN-LAST:event_jLastPageBtnActionPerformed

    private void jWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWriteBtnActionPerformed

    }//GEN-LAST:event_jWriteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMg2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jActionPnl;
    private javax.swing.JLabel jAvgPnl;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JLabel jEngPnl;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstPageBtn;
    private javax.swing.JPanel jInfoPnl;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JLabel jKorPnl;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastPageBtn;
    private javax.swing.JLabel jMathPnl;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JLabel jNamePnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextPageBtn;
    private javax.swing.JPanel jPagePnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrevPageBtn;
    private javax.swing.JLabel jRankPnl;
    private javax.swing.JTextField jRankTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JButton jWherePageBtn;
    private javax.swing.JButton jWriteBtn;
    // End of variables declaration//GEN-END:variables
}
