
import java.awt.FileDialog;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class ScoreSwings extends JFrame {
    
    /**
     * Creates new form ScoreSwings
     */
    public ScoreSwings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jConditionPnl = new javax.swing.JPanel();
        sLabel1 = new javax.swing.JLabel();
        sNameTxt = new javax.swing.JTextField();
        sInsertBtn = new javax.swing.JButton();
        sDeleteBtn = new javax.swing.JButton();
        sloadBtn = new javax.swing.JButton();
        sLabel2 = new javax.swing.JLabel();
        sScoreTxt = new javax.swing.JTextField();
        sUpdateBtn = new javax.swing.JButton();
        sSearchBtn = new javax.swing.JButton();
        sWriteBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jResultPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jConditionPnl.setLayout(new java.awt.GridLayout(2, 0));

        sLabel1.setText("이름 :");
        jConditionPnl.add(sLabel1);
        jConditionPnl.add(sNameTxt);

        sInsertBtn.setText("추가하기");
        sInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sInsertBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sInsertBtn);

        sDeleteBtn.setText("삭제하기");
        sDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDeleteBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sDeleteBtn);

        sloadBtn.setText("파일읽기");
        sloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sloadBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sloadBtn);

        sLabel2.setText("점수 :");
        jConditionPnl.add(sLabel2);

        sScoreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sScoreTxtActionPerformed(evt);
            }
        });
        jConditionPnl.add(sScoreTxt);

        sUpdateBtn.setBackground(new java.awt.Color(102, 255, 153));
        sUpdateBtn.setForeground(new java.awt.Color(255, 153, 255));
        sUpdateBtn.setText("변경하기");
        sUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUpdateBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sUpdateBtn);

        sSearchBtn.setText("조회하기");
        sSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSearchBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sSearchBtn);

        sWriteBtn.setText("파일쓰기");
        sWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sWriteBtnActionPerformed(evt);
            }
        });
        jConditionPnl.add(sWriteBtn);

        getContentPane().add(jConditionPnl);

        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jResultPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//    SButton clickedObj;
    StudentSwings2 clickedStudent;
    Vector<StudentSwings2> totalList = new Vector();
    Vector showList;
    
    private void sScoreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sScoreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sScoreTxtActionPerformed
   
    private void sInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sInsertBtnActionPerformed
//        this.insertCompenent(this.sNameTxt.getText() + " " + this.sScoreTxt.getText() + " " + 0 + " " + 0);
        StudentSwings2 student = new StudentSwings2(this.sNameTxt.getText() + " " + this.sScoreTxt.getText() + " " + 0 + " " + 0);
        totalList.add(student);
        showTotalList();
    }//GEN-LAST:event_sInsertBtnActionPerformed
    
    private void showTotalList() {
        showList = totalList;
        showList();
    }
    
    private void showList() {
        this.jResultPnl.removeAll();
        
        for (int i = 0; i < showList.size(); i++)   {
            StudentSwings2 student = (StudentSwings2)showList.get(i);
            SButton obj = new SButton(student);
            this.jResultPnl.add(obj);
//          @Override
            obj.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SButton obj = (SButton)evt.getSource();
                    StudentSwings2 student = obj.getstudent();
                    sNameTxt.setText(student.getName());
                    sScoreTxt.setText("" + student.getKor());
                    clickedStudent = student;
            }
        });
//        obj.addActionListener(new ActionListener()  {
//            public void actionPerformed(ActionEvent e)  {
//                SButton s = (SButton)e.getSource();
//                StudentSwings2 sd = s.getstudent();
//                sNameTxt.setText(sd.getName());
//                sScoreTxt.setText("" + sd.getKor());
//            }
//        });
        }
        this.pack();
    }
    
    private void sUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUpdateBtnActionPerformed
        if(clickedStudent == null)  {
            return;
        }
        clickedStudent.setName(this.sNameTxt.getText());
        clickedStudent.setKor(Integer.parseInt(this.sScoreTxt.getText()));
        
        showTotalList();
        clickedStudent = null;
    }//GEN-LAST:event_sUpdateBtnActionPerformed

    private void sDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDeleteBtnActionPerformed
        if(clickedStudent == null)    {
            return;
        }
        totalList.remove(clickedStudent);
        showTotalList();
        clickedStudent = null;
    }//GEN-LAST:event_sDeleteBtnActionPerformed
   
    public void insertCompenent(String line)    {
            StudentSwings2 obj2 = new StudentSwings2(line);
            totalList.add(obj2);
            showTotalList();
        }
    
    private void sloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sloadBtnActionPerformed
        FileDialog fileDialogOpen = new FileDialog(this, "파일 열기", FileDialog.LOAD);
        fileDialogOpen.setVisible(true);
        String filePath = fileDialogOpen.getDirectory() + fileDialogOpen.getFile();
        sNameTxt.setText(filePath);
        
        try {
            Scanner scn = new Scanner(new File(filePath));
            String line = "";
            while (true)    {
                try {
                    line = scn.nextLine();
                    insertCompenent(line);
                }   catch(Exception e)  {
                    System.out.println("Line : " + line);
                    System.out.println(e.getMessage());
                    e.printStackTrace();
                    break;
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_sloadBtnActionPerformed
    
    Vector searchList = new Vector();
    private void sSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSearchBtnActionPerformed
        searchList.clear();
        String str = this.sNameTxt.getText();
        
        for (int i = 0; i < totalList.size(); i++) {
            StudentSwings2 student = (StudentSwings2)totalList.get(i);
            if(student.getName().contains(str))   {
                searchList.add(student);
            }
        }
        
        showList = searchList;
        showList();
    }//GEN-LAST:event_sSearchBtnActionPerformed

    private void sWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sWriteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sWriteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreSwings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreSwings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreSwings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreSwings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreSwings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jConditionPnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton sDeleteBtn;
    private javax.swing.JButton sInsertBtn;
    private javax.swing.JLabel sLabel1;
    private javax.swing.JLabel sLabel2;
    private javax.swing.JTextField sNameTxt;
    private javax.swing.JTextField sScoreTxt;
    private javax.swing.JButton sSearchBtn;
    private javax.swing.JButton sUpdateBtn;
    private javax.swing.JButton sWriteBtn;
    private javax.swing.JButton sloadBtn;
    // End of variables declaration//GEN-END:variables
}
