
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sshj1
 */
public class MyStore extends javax.swing.JFrame {
    DBManager db;
    /**
     * Creates new form MyStore
     */
    public MyStore() {
        initComponents();
        this.setExtendedState(6);
        db = MySqlDBManager.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jProductInfoBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMainPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jClientMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jProductMenu = new javax.swing.JMenu();
        jProductInfoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jProductInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/캡처.PNG"))); // NOI18N
        jProductInfoBtn.setFocusable(false);
        jProductInfoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jProductInfoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jProductInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductInfoMenuItemActionPerformed(evt);
            }
        });
        jToolBar1.add(jProductInfoBtn);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/캡처2.PNG"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout jMainPaneLayout = new javax.swing.GroupLayout(jMainPane);
        jMainPane.setLayout(jMainPaneLayout);
        jMainPaneLayout.setHorizontalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jMainPaneLayout.setVerticalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jClientMenu.setText("고객관리");

        jMenuItem1.setText("고객정보");
        jClientMenu.add(jMenuItem1);

        jMenuBar1.add(jClientMenu);

        jProductMenu.setText("물품관리");
        jProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductMenuActionPerformed(evt);
            }
        });

        jProductInfoMenuItem.setText("물품정보");
        jProductInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductInfoMenuItemActionPerformed(evt);
            }
        });
        jProductMenu.add(jProductInfoMenuItem);

        jMenuBar1.add(jProductMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
            .addComponent(jMainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMainPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ProductInfoFrm productInfoFrm = null;
    private void jProductInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductInfoMenuItemActionPerformed
        System.out.println("jProductInfoMenuItemActionPerformed");
        if (productInfoFrm == null)    {
            productInfoFrm = new ProductInfoFrm();
            this.jMainPane.add(productInfoFrm);
        }
        productInfoFrm.setVisible(true);
    }//GEN-LAST:event_jProductInfoMenuItemActionPerformed

    private void jProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductMenuActionPerformed
        System.out.println("jProductMenuActionPerformed");
    }//GEN-LAST:event_jProductMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        int result = JOptionPane.showConfirmDialog(null, "Are you sure to exit?", "Confirm Exit",
//                                                 JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        if (result == JOptionPane.YES_OPTION) {
//            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            this.dispose();
//        } else {
//            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDig frm = new LoginDig(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jClientMenu;
    private javax.swing.JDesktopPane jMainPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jProductInfoBtn;
    private javax.swing.JMenuItem jProductInfoMenuItem;
    private javax.swing.JMenu jProductMenu;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
