/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author sshj1
 */
public class DBScore extends JFrame {
    DBManager db;
    int no;
    ArrayList<String[]> list = new ArrayList<>();
    /**
     * Creates new form DBScore
     */
    public DBScore() {
        initComponents();
        db = MySqlDBManager.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jModelPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMathTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jCommandPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jModelPnl.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("이름");
        jModelPnl.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("국어");
        jModelPnl.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("영어");
        jModelPnl.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("수학");
        jModelPnl.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("평균");
        jModelPnl.add(jLabel5);

        jNameTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jModelPnl.add(jNameTxt);

        jKorTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jKorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jModelPnl.add(jKorTxt);

        jEngTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jEngTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jModelPnl.add(jEngTxt);

        jMathTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jMathTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jModelPnl.add(jMathTxt);

        jAvgTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jAvgTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jModelPnl.add(jAvgTxt);

        jCommandPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jCommandPnl.add(jInsertBtn);

        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("jButton3");
        jCommandPnl.add(jButton3);

        jSearchBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jCommandPnl.add(jSearchBtn);

        jUpdateBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jCommandPnl.add(jUpdateBtn);

        jButton4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton4.setText("jButton4");
        jCommandPnl.add(jButton4);

        jDeleteBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jCommandPnl.add(jDeleteBtn);

        jResultPnl.setLayout(new java.awt.GridLayout(0, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jModelPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCommandPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jModelPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCommandPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("formWindowOpened");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("formWindowClosed");
        db.closeConnection();
    }//GEN-LAST:event_formWindowClosing
    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        list = db.executeQuery("select * from student");
        seeData();
    }//GEN-LAST:event_jSearchBtnActionPerformed
    
    private void seeData()  {
        this.jResultPnl.removeAll();
        for (String[] values : list)    {
            JButton obj = new JButton(
                            values[0] + "-" + values[1]);
            jResultPnl.add(obj);
            obj.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton click = (JButton) evt.getSource();
                int setAvg = ((Integer.parseInt(values[2])) + (Integer.parseInt(values[3])) + (Integer.parseInt(values[4]))) / 3;
                jNameTxt.setText(values[1]);
                jKorTxt.setText(values[2]);
                jEngTxt.setText(values[3]);
                jMathTxt.setText(values[4]);
                jAvgTxt.setText("" + setAvg);
                no = Integer.parseInt(values[0]);
                }
            }
        );
        }
        this.pack();
        list.clear();
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        String sql = "insert into student(name, kor, eng, math) values("
                + "'" + this.jNameTxt.getText() + "'"
                + ",'" + this.jKorTxt.getText() + "'"
                + ",'" + this.jEngTxt.getText() + "'"
                + ",'" + this.jMathTxt.getText() + "');";
        try {
            db.executeUpdate(sql);
            System.out.println(" 추가완료!! ");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(" 추가실패... ");
        }
        this.jSearchBtn.doClick();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        String sql = "Delete FROM student WHERE no = '" + no + "';";
        try {
            db.executeUpdate(sql);
            System.out.println(no + " 삭제완료!! ");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(no + " 삭제실패... ");
        }
        
        this.jSearchBtn.doClick();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        String sql = "UPDATE student SET name = "
                + "'" + this.jNameTxt.getText() + "'"
                + ", kor = " + this.jKorTxt.getText() + ""
                + ", eng = " + this.jEngTxt.getText() + ""
                + ", math = " + this.jMathTxt.getText() + " WHERE no = '" + no + "';";
        try {
            db.executeUpdate(sql);
            System.out.println(no + " 데이터 업데이트 완료!! ");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(no + " 업데이트실패... ");
        }
        this.jSearchBtn.doClick();
    }//GEN-LAST:event_jUpdateBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jCommandPnl;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jMathTxt;
    private javax.swing.JPanel jModelPnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
